---

- hosts: all
  become: true

  tasks:
    
    - name: Creare chiavi ssh
      community.crypto.openssh_keypair:
        path: /tmp/id_key_genericuser
        size: 4096
        type: rsa

    - name: Installa Python 3.8
      ansible.builtin.apt:
        update_cache: yes
        name:
          - python3.8
          - python3.8-venv
          - python3-pip
        state: present

    - name: Usa python 3.8
      ansible.builtin.set_fact:
        ansible_python_interpreter: /usr/bin/python3.8

    - name: Installa docker
      ansible.builtin.apt:
        update_cache: yes
        name: docker.io
        state: present
    
    - name: Copia Dockerfile 
      ansible.builtin.copy:
        src: /Users/giuliagianfrancesco/formazione_cm/Dockerfile
        dest: /tmp/Dockerfile
    

    - name: Build container ubuntu
      community.docker.docker_image:
        build:
          path: /tmp/
        name: immagine_dockerfile
        source: build
    
    - name: Crea rete docker
      community.docker.docker_network:
        name: rete_docker
        ipam_config:
          - subnet: 172.20.0.0/24
    
    - name: Run container ubuntu
      community.docker.docker_container:
        name: mio_ubuntu
        image: immagine_dockerfile
        networks: 
          - name: rete_docker
            ipv4_address: "172.20.0.2"
    

