---
- name: Check Docker installato
  ansible.builtin.command: which docker
  register: docker_check
  ignore_errors: true
  changed_when: false

- name: Check Podman installato
  ansible.builtin.command: which podman
  register: podman_check
  ignore_errors: true
  changed_when: false

- name: Set fact docker_installed
  ansible.builtin.set_fact:
    docker_installed: "{{ docker_check.rc == 0 }}"

- name: Set fact podman_installed
  ansible.builtin.set_fact:
    podman_installed: "{{ podman_check.rc == 0 }}"

- name: Configurare registro Docker
  community.docker.docker_container:
    name: mio_registro
    image: registry:2
    restart_policy: always
    ports:
      - 5000:5000
  when: docker_installed

- name: Configurare registro Podman
  containers.podman.podman_container:
    name: mio_registro
    image: registry:2
    restart_policy: always
    ports:
      - 5000:5000
  when: podman_installed and not docker_installed
  
